name: 'Semantic Versioning'
description: 'Detect semantic version out of tag, branch and commit information'
author: 'Mitigram'

inputs:
  prerelease:
    description: |
      Label to use for pre-release tags (will override branch information)
    default: ""
    required: false
  namespace:
    description: |
      Namespacing prefix for environment variables, empty to disable
    default: "CI"
    required: false
  options:
    description: |
      Additional options to semver, -v to print out path of found binaries
    required: false
    default: ""
  tags:
    description: |
      Regular expression matching the tags that semver computation should
      consider as versioning tags. The default is a possibe letter v, possibly
      followed by some spaces, followed by a dotted version number with at least
      a major version number.
    required: false
    default: '^v?[[:space:]]*[0-9]+(\.[0-9]+(\.[0-9]+)?)?'

outputs:
  semver:
    description: "Semantic Version"
    value: ${{ steps.semver.outputs.semver }}
  version:
    description: "Version number: major.minor.patch"
    value: ${{ steps.semver.outputs.version }}
  branch:
    description: "Git branch"
    value: ${{ steps.semver.outputs.branch }}
  branch-short:
    description: "Git branch short name, i.e. everything after trailing slash"
    value: ${{ steps.semver.outputs.branch-short }}
  tag:
    description: "Current relevant git tag"
    value: ${{ steps.semver.outputs.tag }}
  commit-sha:
    description: "Full git commit revision"
    value: ${{ steps.semver.outputs.commit-sha }}
  commit-short-sha:
    description: "Short git commit revision"
    value: ${{ steps.semver.outputs.commit-short-sha }}

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/semver.sh \
          -p '${{ inputs.prerelease }}' \
          -x '${{ inputs.namespace }}' \
          -t '${{ inputs.tags }}' \
          ${{ inputs.options }} \
          -- \
            '${{ github.ref }}'
      id: semver
      shell: bash
